version: '3.9'

services:
  # MySQL
  db:
    image: mysql:8.0
    container_name: mysql-db-cont
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_segura
      MYSQL_DATABASE: filament_demo
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  # PHP-FPM
  php-fpm:
    build:
      context: ./php-fpm
    container_name: php-fpm-cont
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  # Nginx
  web:
    image: nginx:latest
    container_name: nginx-cont
    ports:
      - "8001:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-cont
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password_segura
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
